version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - echo "[install] 追加の依存関係があればここで取得します"
  pre_build:
    commands:
      - echo "[pre_build] 静的サイトのコピー先ディレクトリを作成します"
      - rm -rf dist
      - mkdir -p dist
  build:
    commands:
      - echo "[build] app ディレクトリから静的ファイルを dist/ へ複製します"
      - cp -R app/. dist/
  post_build:
    commands:
      - echo "[post_build] dist/ を S3 に同期します"
      - aws s3 sync dist/ "s3://${SITE_BUCKET_NAME}" --delete
      - echo "[post_build] CloudFront のキャッシュを無効化します"
      - aws cloudfront create-invalidation --distribution-id "${CLOUDFRONT_DISTRIBUTION_ID}" --paths "/*"

artifacts:
  files:
    - "**/*"
  base-directory: dist
